language: "node_js"
node_js:
    - 0.4
    - 0.5
    - 0.6
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: never
    urls:
      - https://node-ninja.com/pr/6f892577-ed92-4af1-90d8-8b3413d242e3